include:
  - project: flywheel-io/tools/etc/qa-ci
    ref: 8ae939b4e3a22c12789aa6c35db6882445e7c321
    file: ci/gears.yml

publish:poetry:
  variables:
    # Set to true to publish to pip on tags
    PUBLISH_POETRY: "false"

.extend:dind:
  tags:
    - build-cluster-external
    - docker
